import { PrivateWallet } from "interfaces/privateWallet";
import { SheredWallet } from "interfaces/sheredWallet";

export const wallets: Array<PrivateWallet | SheredWallet> = [
  {
    isPrivate: true,
    id: "1",
    name: "mój portfel",
    expenses: [
      {
        id: 1,
        name: "makaron",
        value: 4.5,
        currency: "PLN",
        date: "01-01-2020",
        isCurrent: true,
        category: { id: 1, name: "jedzenie" },
      },
      {
        id: 2,
        name: "lidl",
        value: 43.5,
        currency: "PLN",
        date: "03-01-2020",
        isCurrent: true,
        category: { id: 1, name: "jedzenie" },
      },
      {
        id: 1,
        name: "makaron",
        value: 104.5,
        currency: "PLN",
        date: "01-01-2020",
        isCurrent: true,
        category: { id: 2, name: "mieszkanie" },
      },
      {
        id: 2,
        name: "lidl",
        value: 43.5,
        currency: "PLN",
        date: "03-01-2020",
        isCurrent: true,
        category: { id: 2, name: "mieszkanie" },
      },
      {
        id: 2,
        name: "lidl",
        value: 323.5,
        currency: "PLN",
        date: "03-01-2020",
        isCurrent: true,
        category: { id: 3, name: "samochód" },
      },
      {
        id: 2,
        name: "lidl",
        value: 213.5,
        currency: "PLN",
        date: "03-01-2020",
        isCurrent: true,
        category: { id: 4, name: "nauka" },
      },
    ],
    incomes: [
      {
        id: "1",
        name: "wypłata",
        value: 4342,
        currency: "PLN",
        date: "01-01-2020",
        category: { id: 2, name: "praca" },
      },
      {
        id: "2",
        name: "stypendium",
        value: 600,
        currency: "PLN",
        date: "03-01-2020",
        category: { id: 3, name: "studia" },
      },
    ],
    sumExpenses: 1234.45,
    sumIncomes: 4321.12,
    expensesCategories: [
      { id: 1, name: "jedzenie" },
      { id: 2, name: "praca" },
      { id: 3, name: "studia" },
    ],
    incomesCategories: [],
    dateFrom: new Date(2020, 1),
    dateTo: new Date(2020, 2),
    currency: "PLN",
    balance: 2345,
  },
  {
    isPrivate: false,
    id: "2",
    name: "mieszkanie",
    expenses: [
      {
        id: 1,
        name: "makaron",
        value: 4.5,
        currency: "PLN",
        date: "01-01-2020",
        isCurrent: true,
        owner: {
          id: "1",
          username: "Stefan",
          email: "stefan@wp.pl",
        },
        category: { id: 1, name: "jedzenie" },
        users: { 1: true, 2: false, 3: true },
      },
    ],
    sumExpenses: 1234.45,
    categories: [{ id: 1, name: "jedzenie" }],
    dateFrom: new Date(2020, 1),
    dateTo: new Date(2020, 2),
    users: [
      {
        id: "1",
        username: "Stefan",
        email: "stefan@wp.pl",
      },
      { id: "2", username: "Marta", email: "marta@wp.pl" },
      {
        id: "3",
        username: "Stefan2",
        email: "stefan.nowak@wp.pl",
      },
    ],
    currency: "PLN",
    balance: 2345,
  },
];
